### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by nhenriksen** [nhenriksen/dunk#1]
- [ ] Convert timerge step from shell execution of Parmed to pure python Parmed
- [ ] Separate simulation setup and run so that user can edit cntrl settings
- [ ] Add equilibration step
- [ ] Is timerge really needed for the decharge/recharge step?
